version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.3.0
    - 18.3.3
    - 18.3.4
    - 18.5.0
  - dependency-name: simple-git
    versions:
    - 2.32.0
    - 2.36.0
  - dependency-name: "@octokit/graphql"
    versions:
    - 4.5.9
